export const DocumentRequestTypeEnum = {
  NORMAL_REQUEST: 'DTRA001',
  PRODUCTION_ORDER: 'DTRA002',
  PRODUCTION_GR_PLAN: 'DTRA003',
  PURCHASE_GR_PLAN: 'DTRA004',
  PRODUCTION_GI_PLAN: 'DTRA005',
  SHIPPING_GI_PLAN: 'DTRA006',
  BOM: 'DTRA007',
  ECR: 'DTRA008',
  INSPECTION_RESULT: 'DTRA009',
  PLAN_BOM: 'DTRA010',
  PM_RESULT: 'DTRA011'
};

export const RequestParameterTypeEnum = {
  INTERNAL_ENTITY_ID: 'INTERNAL_ENTITY_ID'
};
