# build in local
FROM nginx:stable-alpine

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf 
COPY ./build /usr/share/nginx/html
COPY .env /usr/share/nginx/html/.env

RUN apk add --update nodejs
RUN apk add --update npm
RUN npm install -g runtime-env-cra@0.2.2

WORKDIR /usr/share/nginx/html

EXPOSE 80

CMD ["/bin/sh", "-c", "runtime-env-cra && nginx -g \"daemon off;\""]