import { defaultColDef } from './defaultColDef';

export const productionResultGridConfig = {
  master: [
    {
      ...defaultColDef,
      filter: false,
      suppressColumnsToolPanel: true,
      suppressMovable: true,
      sortable: false,
      checkboxSelection: true,
      headerCheckboxSelection: true,
      headerCheckboxSelectionFilteredOnly: true,
      maxWidth: 21,
      colId: "0",
      pinned: "left"
    },
    {
      ...defaultColDef,
      filter: false,
      suppressMovable: true,
      sortable: false,
      field: "row_index",
      headerName: "No.",
      valueGetter: "node.rowIndex + 1",
      minWidth: 45,
      colId: "row_index",
      width: 45,
      pinned: "left"
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: "planDate",
      headerName: "Plan Date",
      colId: "planDate",
      tooltipField: "planDate",
      width: 200,
      pinned: "left"
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: "lineCode",
      headerName: "Line Code",
      colId: "lineCode",
      tooltipField: "lineCode",
      width: 200,
      pinned: "left"
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: "lineName",
      headerName: "Line Name",
      colId: "lineName",
      tooltipField: "lineName",
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'process',
      headerName: 'Process',
      colId: 'process',
      tooltipField: 'process',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'finalYn',
      headerName: 'Final (Y/N)',
      colId: 'finalYn',
      tooltipField: 'finalYn',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'workstation',
      headerName: 'Workstation',
      colId: 'workstation',
      tooltipField: 'workstation',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'reflect',
      headerName: 'Reflect (Y/N)',
      colId: 'reflect',
      tooltipField: 'reflect',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'prodOrderNo',
      headerName: 'Production Order',
      colId: 'prodOrderNo',
      tooltipField: 'prodOrderNo',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'modelID',
      headerName: 'Model ID',
      colId: 'modelID',
      tooltipField: 'modelID',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'modelCode',
      headerName: 'Model Code',
      colId: 'modelCode',
      tooltipField: 'modelCode',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'modelDesc',
      headerName: 'Model Desc',
      colId: 'modelDesc',
      tooltipField: 'modelDesc',
      width: 240,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'modelVersion',
      headerName: 'Model Version',
      colId: 'modelVersion',
      tooltipField: 'modelVersion',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'status',
      headerName: 'Status',
      colId: 'status',
      tooltipField: 'status',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'prodStatus',
      headerName: 'Production Status',
      colId: 'prodStatus',
      tooltipField: 'prodStatus',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'poType',
      headerName: 'PO Type',
      colId: 'poType',
      tooltipField: 'poType',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'planStartTime',
      headerName: 'Plan Start Time',
      colId: 'planStartTime',
      tooltipField: 'planStartTime',
      width: 240,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'planEndTime',
      headerName: 'Plan End Time',
      colId: 'planEndTime',
      tooltipField: 'planEndTime',
      width: 240,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'actualStartTime',
      headerName: 'Actual Start Time',
      colId: 'actualStartTime',
      tooltipField: 'actualStartTime',
      width: 240,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'actualEndTime',
      headerName: 'Actual End Time',
      colId: 'actualEndTime',
      tooltipField: 'actualEndTime',
      width: 240,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'planQty',
      headerName: 'Plan Qty',
      colId: 'planQty',
      tooltipField: 'planQty',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'actualQty',
      headerName: 'Actual Qty',
      colId: 'actualQty',
      tooltipField: 'actualQty',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'targetQty',
      headerName: 'Target Qty',
      colId: 'targetQty',
      tooltipField: 'targetQty',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'balQty',
      headerName: 'Bal Qty',
      colId: 'balQty',
      tooltipField: 'balQty',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'defectQty',
      headerName: 'Defect Qty',
      colId: 'defectQty',
      tooltipField: 'defectQty',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'tactTime',
      headerName: 'Tact Time',
      colId: 'tactTime',
      tooltipField: 'tactTime',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'factoryName',
      headerName: 'Factory',
      colId: 'factoryName',
      tooltipField: 'factoryName',
      width: 240,
      hide: true
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'plant',
      headerName: 'Plant',
      colId: 'plant',
      tooltipField: 'plant',
      width: 240,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'processType',
      headerName: 'Process Type',
      colId: 'processType',
      tooltipField: 'processType',
      width: 260,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'planID',
      headerName: 'Plan ID',
      colId: 'planID',
      tooltipField: 'planID',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'topPO',
      headerName: 'Top PO',
      colId: 'topPO',
      tooltipField: 'topPO',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'topModelCode',
      headerName: 'Top Model Code',
      colId: 'topModelCode',
      tooltipField: 'topModelCode',
      width: 240,
    }
  ],
  detail: [
    {
      ...defaultColDef,
      filter: false,
      suppressColumnsToolPanel: true,
      suppressMovable: true,
      sortable: false,
      checkboxSelection: true,
      headerCheckboxSelection: true,
      headerCheckboxSelectionFilteredOnly: true,
      maxWidth: 21,
      colId: "0",
      pinned: "left"
    },
    {
      ...defaultColDef,
      filter: false,
      suppressMovable: true,
      sortable: false,
      field: "row_index",
      headerName: "No.",
      valueGetter: "node.rowIndex + 1",
      minWidth: 45,
      colId: "row_index",
      width: 45,
      pinned: "left"
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: "planDate",
      headerName: "Plan Date",
      colId: "planDate",
      tooltipField: "planDate",
      width: 200,
      pinned: "left"
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: "lineCode",
      headerName: "Line Code",
      colId: "lineCode",
      tooltipField: "lineCode",
      width: 200,
      pinned: "left"
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: "lineName",
      headerName: "Line Name",
      colId: "lineName",
      tooltipField: "lineName",
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'process',
      headerName: 'Process',
      colId: 'process',
      tooltipField: 'process',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'finalYn',
      headerName: 'Final (Y/N)',
      colId: 'finalYn',
      tooltipField: 'finalYn',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'workStation',
      headerName: 'work Station',
      colId: 'workStation',
      tooltipField: 'workStation',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'reflect',
      headerName: 'Reflect (Y/N)',
      colId: 'reflect',
      tooltipField: 'reflect',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'prodOrderNo',
      headerName: 'Production Order',
      colId: 'prodOrderNo',
      tooltipField: 'prodOrderNo',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'modelID',
      headerName: 'Model ID',
      colId: 'modelID',
      tooltipField: 'modelID',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'modelCode',
      headerName: 'Model Code',
      colId: 'modelCode',
      tooltipField: 'modelCode',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'modelDesc',
      headerName: 'Model Desc',
      colId: 'modelDesc',
      tooltipField: 'modelDesc',
      width: 240,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'modelVersion',
      headerName: 'Model Version',
      colId: 'modelVersion',
      tooltipField: 'modelVersion',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'serialNo',
      headerName: 'Serial No',
      colId: 'serialNo',
      tooltipField: 'serialNo',
      width: 300,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'productionTime',
      headerName: 'Production Time',
      colId: 'productionTime',
      tooltipField: 'productionTime',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'boxLabel',
      headerName: 'Box Label',
      colId: 'boxLabel',
      tooltipField: 'boxLabel',
      width: 300,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'tactTime',
      headerName: 'Tact Time',
      colId: 'tactTime',
      tooltipField: 'tactTime',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'actTacTime',
      headerName: 'Actual Tact Time',
      colId: 'actTacTime',
      tooltipField: 'actTacTime',
      width: 200,
    }
  ],
  detailCancel: [
    {
      ...defaultColDef,
      filter: false,
      suppressColumnsToolPanel: true,
      suppressMovable: true,
      sortable: false,
      checkboxSelection: true,
      headerCheckboxSelection: true,
      headerCheckboxSelectionFilteredOnly: true,
      maxWidth: 21,
      colId: "0",
      pinned: "left"
    },
    {
      ...defaultColDef,
      filter: false,
      suppressMovable: true,
      sortable: false,
      field: "row_index",
      headerName: "No.",
      valueGetter: "node.rowIndex + 1",
      minWidth: 60,
      colId: "row_index",
      width: 60,
      pinned: "left"
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: "planDate",
      headerName: "Plan Date",
      colId: "planDate",
      tooltipField: "planDate",
      width: 200,
      pinned: "left"
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: "lineCode",
      headerName: "Line Code",
      colId: "lineCode",
      tooltipField: "lineCode",
      width: 200,
      pinned: "left"
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: "lineName",
      headerName: "Line Name",
      colId: "lineName",
      tooltipField: "lineName",
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'process',
      headerName: 'Process',
      colId: 'process',
      tooltipField: 'process',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'finalYn',
      headerName: 'Final (Y/N)',
      colId: 'finalYn',
      tooltipField: 'finalYn',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'workStation',
      headerName: 'work Station',
      colId: 'workStation',
      tooltipField: 'workStation',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'reflect',
      headerName: 'Reflect (Y/N)',
      colId: 'reflect',
      tooltipField: 'reflect',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'prodOrderNo',
      headerName: 'Production Order',
      colId: 'prodOrderNo',
      tooltipField: 'prodOrderNo',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'modelID',
      headerName: 'Model ID',
      colId: 'modelID',
      tooltipField: 'modelID',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'modelCode',
      headerName: 'Model Code',
      colId: 'modelCode',
      tooltipField: 'modelCode',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'modelDesc',
      headerName: 'Model Desc',
      colId: 'modelDesc',
      tooltipField: 'modelDesc',
      width: 240,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'modelVersion',
      headerName: 'Model Version',
      colId: 'modelVersion',
      tooltipField: 'modelVersion',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'serialNo',
      headerName: 'Serial No',
      colId: 'serialNo',
      tooltipField: 'serialNo',
      width: 300,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'productionTime',
      headerName: 'Production Time',
      colId: 'productionTime',
      tooltipField: 'productionTime',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'boxLabel',
      headerName: 'Box Label',
      colId: 'boxLabel',
      tooltipField: 'boxLabel',
      width: 300,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'tactTime',
      headerName: 'Tact Time',
      colId: 'tactTime',
      tooltipField: 'tactTime',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'actTacTime',
      headerName: 'Actual Tact Time',
      colId: 'actTacTime',
      tooltipField: 'actTacTime',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'cancelReason',
      headerName: 'Cancel Reason',
      colId: 'cancelReason',
      tooltipField: 'cancelReason',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'cancelDetail',
      headerName: 'Cancel Detail',
      colId: 'cancelDetail',
      tooltipField: 'cancelDetail',
      width: 200,
    },
    {
      ...defaultColDef,
      suppressMovable: true,
      field: 'factoryName',
      headerName: 'Factory',
      colId: 'factoryName',
      tooltipField: 'factoryName',
      width: 240,
    }
  ]
}